create table if not exists public.character_saves (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  character_id text not null,
  name text not null,
  data jsonb not null,
  updated_at timestamptz not null default now(),
  unique(user_id, character_id)
);

create table if not exists public.ai_memories (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  character_id text not null,
  memory text not null,
  importance int not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  character_id text not null,
  role text not null check (role in ('user','assistant','system')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists character_saves_user_idx on public.character_saves(user_id);
create index if not exists memories_lookup_idx on public.ai_memories(user_id, character_id, importance desc, created_at desc);
create index if not exists messages_lookup_idx on public.chat_messages(user_id, character_id, created_at desc);

alter table public.character_saves enable row level security;
alter table public.ai_memories enable row level security;
alter table public.chat_messages enable row level security;

drop policy if exists "users read own characters" on public.character_saves;
drop policy if exists "users insert own characters" on public.character_saves;
drop policy if exists "users update own characters" on public.character_saves;
drop policy if exists "users delete own characters" on public.character_saves;
drop policy if exists "users read own memories" on public.ai_memories;
drop policy if exists "users write own memories" on public.ai_memories;
drop policy if exists "users read own messages" on public.chat_messages;
drop policy if exists "users write own messages" on public.chat_messages;

create policy "users read own characters" on public.character_saves for select to authenticated using (auth.uid() = user_id);
create policy "users insert own characters" on public.character_saves for insert to authenticated with check (auth.uid() = user_id);
create policy "users update own characters" on public.character_saves for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users delete own characters" on public.character_saves for delete to authenticated using (auth.uid() = user_id);

create policy "users read own memories" on public.ai_memories for select to authenticated using (auth.uid() = user_id);
create policy "users write own memories" on public.ai_memories for insert to authenticated with check (auth.uid() = user_id);

create policy "users read own messages" on public.chat_messages for select to authenticated using (auth.uid() = user_id);
create policy "users write own messages" on public.chat_messages for insert to authenticated with check (auth.uid() = user_id);

grant select, insert, update, delete on public.character_saves to authenticated;
grant select, insert on public.ai_memories to authenticated;
grant select, insert on public.chat_messages to authenticated;
grant usage, select on sequence public.character_saves_id_seq to authenticated;
grant usage, select on sequence public.ai_memories_id_seq to authenticated;
grant usage, select on sequence public.chat_messages_id_seq to authenticated;
