-- MarioAI online memory database for Supabase
-- Run this in Supabase SQL Editor.
create table if not exists public.character_saves (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  character_id text not null,
  name text not null,
  data jsonb not null,
  updated_at timestamptz not null default now(),
  unique(user_id, character_id)
);

alter table public.character_saves enable row level security;

drop policy if exists "users read own character saves" on public.character_saves;
drop policy if exists "users insert own character saves" on public.character_saves;
drop policy if exists "users update own character saves" on public.character_saves;
drop policy if exists "users delete own character saves" on public.character_saves;

create policy "users read own character saves"
on public.character_saves for select
to authenticated
using (auth.uid() = user_id);

create policy "users insert own character saves"
on public.character_saves for insert
to authenticated
with check (auth.uid() = user_id);

create policy "users update own character saves"
on public.character_saves for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users delete own character saves"
on public.character_saves for delete
to authenticated
using (auth.uid() = user_id);

grant select, insert, update, delete on public.character_saves to authenticated;
grant usage, select on sequence public.character_saves_id_seq to authenticated;

-- Also enable Anonymous Sign-Ins in Supabase Auth settings.
